let prefixes = [
  'dazwischen',
  'zusammen',
  'zwangsum',
  'daneben',
  'dagegen',
  'schwarz',
  'kaputt',
  'hinein',
  'zurück',
  'weiter',
  'gleich',
  'allein',
  'schief',
  'fertig',
  'hängen',
  'kleben',
  'nieder',
  'falsch',
  'wider',
  'breit',
  'krumm',
  'offen',
  'drauf',
  'dahin',
  'klein',
  'durch',
  'davon',
  'daher',
  'dahin',
  'flach',
  'dabei',
  'drein',
  'davor',
  'krank',
  'knapp',
  'dafür',
  'rück',
  'glatt',
  'dazu',
  'bloß',
  'wahr',
  'weis',
  'hohn',
  'lieb',
  'acht',
  'groß',
  'wach',
  'drin',
  'hoch',
  'hier',
  'hops',
  'lahm',
  'quer',
  'klar',
  'fern',
  'fein',
  'fehl',
  'nach',
  'blau',
  'dran',
  'fest',
  'fort',
  'heim',
  'nahe',
  'rein',
  'leer',
  'hops',
  'kurz',
  'kahl',
  'frei',
  'dar',
  'auf',
  'bei',
  'ein',
  'her',
  'tot',
  'alt',
  'eis',
  'hin',
  'los',
  'mit',
  'vor',
  'weg',
  'zu',
  'um',
  'ab',
  'an'
]

let suffixes = [
  ['färben', 'färbt'],
  ['hängen', 'hangen'],
  ['bringen', 'bracht'],
  ['auchen', 'aucht'],
  ['riechen', 'rochen'],
  ['elzen', 'olzen'],
  ['dnen', 'dnet'],
  ['tragen', 'tragen'],
  ['chsen', 'chsen'],
  ['achen', 'acht'],
  ['ünden', 'ündet'],
  ['tehen', 'tanden'],
  ['chnen', 'chnet'],
  ['toßen', 'toßen'],
  ['chten', 'chtet'],
  ['reden', 'redet'],
  ['reten', 'reten'],
  ['alten', 'alten'],
  ['rehen', 'reht'],
  ['ilden', 'ildet'],
  ['erben', 'orben'],
  ['chauen', 'chaut'],
  ['neiden', 'nitten'],
  ['lagen', 'lagen'],
  ['gehen', 'gangen'],
  ['laufen', 'laufen'],
  ['fahren', 'fahren'],
  ['tragen', 'tragen'],
  ['hauen', 'hauen'],
  ['inken', 'unken'],
  ['sehen', 'sehen'],
  ['eifen', 'eift'],
  ['assen', 'asst'],
  ['innen', 'onnen'],
  ['iehen', 'ogen'],
  ['eifen', 'iffen'],
  ['eiben', 'ieben'],
  ['gehen', 'ganden'],
  ['eißen', 'issen'],
  ['iegen', 'ogen'],
  ['inden', 'unden'],
  ['annen', 'annt'],
  // ['ühen', 'üht'],
  ['enken', 'acht'],
  ['enden', 'andt'],
  ['achen', 'acht'],
  ['schen', 'scht'],
  ['ehmen', 'ommen'],
  ['ießen', 'ossen'],
  ['ingen', 'ungen'],
  ['echen', 'ochen'],
  ['ommen', 'ommen'],
  ['ssen', 'ssen'],
  ['tten', 'ttet'],
  ['ören', 'ört'],
  ['ehen', 'anden'],
  ['eln', 'elt'],
  ['ten', 'tet'],
  ['ern', 'ert'],

]
export { prefixes, suffixes }