export default {
  "politisch": ["politisch", "politische", "politischen", "politischen"],
  "gut": ["besser", "gute", "gutes", "gute"],
  "weiß": ["weißen", "weiße", "weißes", "weiße"],
  "amtierend": ["amtierender", "amtierende", "amtierenden", "amtierende"],
  "erfolgreich": ["erfolgreichen", "erfolgreichen", "erfolgreiches", "erfolgreichsten"],
  "groß": ["großen", "größere", "größeres", "große"],
  "anderer": ["anderen", "andere", "anderes", "anderen"],
  "schwer": ["schwerer", "schwerer", "schwere", "schwere"],
  "ehemalig": ["ehemaliger", "ehemaligen", "ehemaligen", "ehemaliger"],
  "absolut": ["absolut", "absoluter", "absoluten", "absolute"],
  "klein": ["kleinen", "kleiner", "kleines", "kleinen"],
  "mittlerer": ["mittleren", "mittleren", "mittleren", "mittlere"],
  "zusätzlich": ["zusätzlich", "zusätzliche", "zusätzliches", "zusätzlichen"],
  "persönlich": ["persönlich", "persönliche", "persönliche", "persönlichen"],
  "modern": ["moderner", "moderner", "modernen", "modernen"],
  "ordentlich": ["ordentlichen", "ordentliche", "ordentliche"],
  "autoritär": ["autoritär", "autoritäre", "autoritäres", "autoritären"],
  "wirklich": ["wirklich", "wirkliche", "wirklichen", "wirkliche"],
  "konkret": ["konkret", "konkrete", "konkretes", "konkrete"],
  "gigantisch": ["gigantischer", "gigantischen", "gigantisches", "gigantische"],
  "geplant": ["geplanten", "geplante", "geplantes", "geplanten"],
  "hart": ["hart", "harte", "harte", "harten"],
  "richtig": ["richtig", "richtige", "richtiges", "richtigen"],
  "weit": ["weit", "weitere", "weiterem", "weitere"],
  "national": ["national", "nationalen", "nationales", "nationale"],
  "allgemein": ["allgemein", "allgemeine", "allgemeinen", "allgemeinen"],
  "verantwortlich": ["verantwortlich", "verantwortliche", "verantwortliche", "verantwortliche"],
  "früh": ["frühen", "frühere", "früheren", "früheren"],
  "spät": ["später", "späte", "späteren", "späten"],
  "einig": ["einig", "einigen", "einig"],
  "ausländisch": ["ausländischen", "ausländischen", "ausländisches", "ausländische"],
  "revolutionär": ["revolutionären", "revolutionäre", "revolutionären", "revolutionären"],
  "alt": ["alten", "älterer", "alten", "alten"],
  "sowjetisch": ["sowjetische", "sowjetische", "sowjetischen", "sowjetische"],
  "kritisch": ["kritische", "kritische", "kritische", "kritische"],
  "britisch": ["britische", "britischen", "britische", "britischen"],
  "wirtschaftlich": ["wirtschaftlichen", "wirtschaftliche", "wirtschaftliche", "wirtschaftlichen"],
  "neu": ["neu", "neue", "neue", "neuerer"],
  "praktisch": ["praktischen", "praktische", "praktische", "praktischen"],
  "blutig": ["blutigen", "blutigen", "blutigen", "blutige"],
  "tief": ["tiefen", "tiefste", "tieferen", "tiefe"],
  "international": ["internationalen", "internationalen", "internationalen", "internationale"],
  "dick": ["dickeren", "dicke", "dickes", "dicken"],
  "schnell": ["schnell", "schnelle", "schnellen", "schnellen"],
  "notwendig": ["notwendig", "notwendige", "notwendiges", "notwendigen"],
  "eng": ["eng", "enge", "engen", "enge"],
  "stark": ["stärksten", "starke", "stärkste", "starke"],
  "indisch": ["indischen", "indischen", "indischen", "indische"],
  "nächster": ["nächsten", "nächsten", "nächsten", "nächsten"],
  "massiv": ["massiv", "massive", "massives", "massiven"],
  "gewaltig": ["gewaltig", "gewaltige", "gewaltiges", "gewaltige"],
  "ständig": ["ständigem", "ständigen", "ständiges", "ständige"],
  "schlecht": ["schlechten", "schlechte", "schlechtes", "schlechte"],
  "mies": ["miesen", "miesen", "miesen", "miesen"],
  "heiß": ["heiß", "heißesten", "heißes", "heißere"],
  "drastisch": ["drastisch", "drastische", "drastischem", "drastischen"],
  "produzierend": ["produzierend", "produzierende", "produzierende", "produzierende"],
  "verstaatlicht": ["verstaatlichten", "verstaatlichte", "verstaatlichten", "verstaatlichter"],
  "mächtig": ["mächtigsten", "mächtige", "mächtigen", "mächtigen"],
  "zweiter": ["zweiter", "zweite", "zweiten"],
  "öffentlich": ["öffentlichen", "öffentlicher", "öffentliches", "öffentliche"],
  "erster": ["ersten", "erster", "ersten", "erste"],
  "gegenwärtig": ["gegenwärtig", "gegenwärtige", "gegenwärtigen", "gegenwärtigen"],
  "erschreckend": ["erschreckendsten", "erschreckende", "erschreckendes", "erschreckenden"],
  "deutlich": ["deutlicher", "deutlichen", "deutliches", "deutliche"],
  "entscheidend": ["entscheidend", "entscheidenden", "entscheidenden", "entscheidenden"],
  "voraussichtlich": ["voraussichtlich", "voraussichtlichen", "voraussichtliches"],
  "gering": ["gering", "geringe", "geringste", "geringere"],
  "beginnend": ["beginnend", "beginnende", "beginnenden", "beginnenden"],
  "hilflos": ["hilflosen", "hilflose", "hilfloses"],
  "rechtsradikal": ["rechtsradikalen", "rechtsradikalen", "rechtsradikales", "rechtsradikale"],
  "damalig": ["damalige", "damalige", "damalige", "damalige"],
  "symbolisch": ["symbolisch", "symbolische", "symbolische", "symbolischen"],
  "angemessen": ["angemessen", "angemessene", "angemessenes", "angemessene"],
  "vergleichbar": ["vergleichbaren", "vergleichbarer", "vergleichbares", "vergleichbare"],
  "heutig": ["heutigen", "heutigen", "heutige", "heutigen"],
  "hoch": ["höchst", "hohe", "hohes", "höhere"],
  "moralisch": ["moralisch", "moralischer", "moralische", "moralische"],
  "fragwürdig": ["fragwürdiger", "fragwürdige", "fragwürdige", "fragwürdige"],
  "dritter": ["dritte", "dritten", "dritte", "dritte"],
  "direkt": ["direkt", "direkter", "direkte", "direkten"],
  "sozial": ["sozialen", "soziale", "sozialen", "soziale"],
  "multikulturell": ["multikultureller", "multikulturelle", "multikulturelles", "multikulturelle"],
  "effektiv": ["effektiveren", "effektive", "effektiveres", "effektive"],
  "gewachsen": ["gewachsenen", "gewachsener", "gewachsene", "gewachsenen"],
  "genau": ["genauer", "genaue", "genaues", "genauer"],
  "angeblich": ["angeblich", "angebliche", "angebliche", "angebliche"],
  "nationalistisch": ["nationalistisch", "nationalistische", "nationalistische", "nationalistischen"],
  "rassistisch": ["rassistisch", "rassistischen", "rassistische", "rassistischen"],
  "rechter": ["rechten", "rechte", "rechten", "rechten"],
  "generell": ["genereller", "generelle", "generelles"],
  "elektronisch": ["elektronischen", "elektronische", "elektronische", "elektronischen"],
  "demokratisch": ["demokratischen", "demokratischen", "demokratisches", "demokratischen"],
  "frei": ["frei", "freie", "freien", "freien"],
  "bestimmt": ["bestimmt", "bestimmten", "bestimmtes", "bestimmten"],
  "prekär": ["prekär", "prekäre", "prekären"],
  "verstärkt": ["verstärkt", "verstärkte", "verstärktem", "verstärkte"],
  "inhaltlich": ["inhaltlich", "inhaltlichen", "inhaltliche", "inhaltlichen"],
  "geeignet": ["geeignete", "geeignete", "geeignetes", "geeignete"],
  "sichtbar": ["sichtbar", "sichtbaren", "sichtbaren", "sichtbaren"],
  "innerer": ["inneren", "innere", "inneren", "innere"],
  "parlamentarisch": ["parlamentarische", "parlamentarische", "parlamentarische", "parlamentarischen"],
  "ernsthaft": ["ernsthaft", "ernsthafte", "ernsthaftes", "ernsthaften"],
  "gewiß": ["gewiß", "gewisser", "gewissem", "gewissen"],
  "eigen": ["eigenen", "eigene", "eigenes", "eigenen"],
  "beachtlich": ["beachtlicher", "beachtliche", "beachtliches", "beachtliche"],
  "vernünftig": ["vernünftig", "vernünftige", "vernünftigen", "vernünftige"],
  "dumm": ["dumm", "dumme", "dummes"],
  "lang": ["lang", "langen", "langem", "längeren"],
  "langfristig": ["langfristig", "langfristigen", "langfristigen", "langfristigen"],
  "unterschiedlich": ["unterschiedlich", "unterschiedlichen", "unterschiedlichen", "unterschiedlichen"],
  "tatsächlich": ["tatsächlich", "tatsächliche", "tatsächliches", "tatsächlicher"],
  "europäisch": ["europäischen", "europäische", "europäische", "europäischen"],
  "überzeugend": ["überzeugend", "überzeugende", "überzeugendes", "überzeugende"],
  "wissenschaftlich": ["wissenschaftlichen", "wissenschaftlichen", "wissenschaftliches", "wissenschaftlichen"],
  "letzter": ["letzten", "letzter", "letzten", "letzten"],
  "täglich": ["täglich", "täglichen", "tägliche", "tägliche"],
  "niedersächsisch": ["niedersächsischen", "niedersächsische", "niedersächsischen", "niedersächsischen"],
  "vergangen": ["vergangenen", "vergangene", "vergangenen", "vergangenen"],
  "25.": ["25.", "25.", "25."],
  "einzeln": ["einzelnen", "einzelnen", "einzelnes", "einzelne"],
  "mutmaßlich": ["mutmaßlichen", "mutmaßlichen", "mutmaßliches", "mutmaßliche"],
  "einzig": ["einziger", "einzige", "einziges", "einzigen"],
  "sogenannter": ["sogenannter", "sogenannte", "sogenanntes", "sogenannte"],
  "mysteriös": ["mysteriöser", "mysteriöse", "mysteriöse", "mysteriösen"],
  "ironisch": ["ironisch", "ironische", "ironische"],
  "weitgehend": ["weitgehend", "weitgehende", "weitgehendes", "weitgehende"],
  "geregelt": ["geregelten", "geregelte", "geregeltes", "geregelten"],
  "regional": ["regionalen", "regionale", "regionale", "regionalen"],
  "bürgerlich": ["bürgerlicher", "bürgerlichen", "bürgerlichen"],
  "jetzig": ["jetzigen", "jetzigen", "jetzige", "jetzigen"],
  "unabhängig": ["unabhängig", "unabhängige", "unabhängiges", "unabhängiger"],
  "ausgesprochen": ["ausgesprochen", "ausgesprochene", "ausgesprochenen"],
  "wichtig": ["wichtig", "wichtige", "wichtigen", "wichtigsten"],
  "häufig": ["häufig", "häufigste", "häufige", "häufigsten"],
  "peinlich": ["peinlich", "peinliche", "peinliches", "peinlichen"],
  "jung": ["jünger", "junge", "junges", "jüngere"],
  "unglaublich": ["unglaublich", "unglaubliche", "unglaubliches"],
  "dringend": ["dringend", "dringende", "dringendes", "dringende"],
  "unerlaubt": ["unerlaubt", "unerlaubter", "unerlaubte"],
  "frisch": ["frische", "frischer", "frische", "frische"],
  "deutsch": ["deutschen", "deutsche", "deutsches", "deutschen"],
  "niedrig": ["niedriger", "niedrige", "niedrigstem", "niedrigen"],
  "teuer": ["teuer", "teure", "teures", "teuren"],
  "kostspielig": ["kostspielig", "kostspielige", "kostspielige", "kostspielige"],
  "fehlend": ["fehlendem", "fehlende", "fehlende", "fehlende"],
  "vermeintlich": ["vermeintlich", "vermeintliche", "vermeintlichen", "vermeintlicher"],
  "sicher": ["sicher", "sichere", "sicheren", "sichere"],
  "hessisch": ["hessische", "hessische", "hessischen", "hessischen"],
  "laut": ["laut", "lauter", "lauten", "lauten"],
  "privat": ["privaten", "privater", "privaten", "privater"],
  "beliebt": ["beliebter", "beliebte", "beliebtes", "beliebten"],
  "gemeinsam": ["gemeinsamen", "gemeinsamen", "gemeinsamen", "gemeinsamen"],
  "ernst": ["ernst", "ernster", "ernstes", "ernsten"],
  "angeschlagen": ["angeschlagene", "angeschlagenen", "angeschlagenen", "angeschlagener"],
  "juristisch": ["juristisch", "juristische", "juristisches", "juristischen"],
  "brutal": ["brutal", "brutale", "brutale", "brutalster"],
  "unmittelbar": ["unmittelbar", "unmittelbaren", "unmittelbares", "unmittelbarer"],
  "organisiert": ["organisierter", "organisierten", "organisierten", "organisierter"],
  "klar": ["klarer", "klare", "klaren", "klare"],
  "billig": ["billiger", "billiger", "billigere", "billigere"],
  "heftig": ["heftig", "heftigste", "heftigem", "heftigen"],
  "österreichisch": ["österreichischen", "österreichischen", "österreichischen", "österreichische"],
  "wahr": ["wahr", "wahren", "wahre", "wahre"],
  "zuständig": ["zuständig", "zuständige", "zuständige", "zuständigen"],
  "benachbart": ["benachbarten", "benachbarten", "benachbarte", "benachbarten"],
  "knapp": ["knapp", "knappe", "knappes", "knappe"],
  "heimisch": ["heimischen", "heimische", "heimischen", "heimischen"],
  "fremd": ["fremd", "fremden", "fremden", "fremden"],
  "diplomatisch": ["diplomatischer", "diplomatische", "diplomatische", "diplomatische"],
  "grenzüberschreitend": ["grenzüberschreitenden", "grenzüberschreitende", "grenzüberschreitendes", "grenzüberschreitenden"],
  "neutral": ["neutralen", "neutralen", "neutralen", "neutrale"],
  "betroffen": ["betroffen", "betroffenen", "betroffene", "betroffenen"],
  "gegenseitig": ["gegenseitig", "gegenseitige", "gegenseitigen", "gegenseitigen"],
  "unterer": ["unteren", "unteren", "unteren", "unteren"],
  "schweizerisch": ["schweizerische", "schweizerische", "schweizerischen", "schweizerischer"],
  "möglich": ["möglich", "mögliche", "mögliche", "möglichen"],
  "jährlich": ["jährlich", "jährliche", "jährliche", "jährlichen"],
  "üblich": ["üblich", "üblichen", "übliche", "üblichen"],
  "anhaltend": ["anhaltend", "anhaltende", "anhaltenden", "anhaltende"],
  "bedeutend": ["bedeutendsten", "bedeutende", "bedeutendes", "bedeutenden"],
  "fertig": ["fertig", "fertige", "fertigen", "fertigen"],
  "enorm": ["enorm", "enorme", "enormes", "enorme"],
  "westlich": ["westlich", "westliche", "westliche", "westlichen"],
  "amerikanisch": ["amerikanische", "amerikanische", "amerikanisches", "amerikanischen"],
  "überwiegend": ["überwiegend", "überwiegende", "überwiegenden"],
  "südlich": ["südlich", "südlichsten", "südliche", "südlichen"],
  "berühmt": ["berühmtesten", "berühmte", "berühmten", "berühmten"],
  "jahrelang": ["jahrelanger", "jahrelange", "jahrelangem", "jahrelange"],
  "intensiv": ["intensiv", "intensiver", "intensives", "intensiveren"],
  "nah": ["näher", "näheren", "näherem", "nähere"],
  "gelegen": ["gelegen", "gelegenen", "gelegene", "gelegenen"],
  "flexibel": ["flexibler", "flexiblere", "flexiblen", "flexiblere"],
  "gleich": ["gleichen", "gleichen", "gleiche", "gleichen"],
  "herkömmlich": ["herkömmlichen", "herkömmlichen", "herkömmlichen", "herkömmlichen"],
  "islamisch": ["islamischem", "islamischen", "islamischem", "islamischen"],
  "rasch": ["rasch", "rasche", "raschen", "raschen"],
  "ganz": ["ganz", "ganzen", "ganzen", "ganze"],
  "zentral": ["zentralen", "zentrale", "zentrales", "zentrale"],
  "gebaut": ["gebauten", "gebauten", "gebautes", "gebaute"],
  "staatlich": ["staatliche", "staatlicher", "staatlichen", "staatlichen"],
  "lokal": ["lokalen", "lokale", "lokale", "lokalen"],
  "offiziell": ["offiziell", "offiziellen", "offiziellen", "offiziellen"],
  "heilig": ["heiligen", "heiligen", "heilige", "heiligen"],
  "achter": ["achten", "achter", "achten"],
  "oberer": ["oberen", "obersten", "oberste", "obersten"],
  "bewaffnet": ["bewaffneten", "bewaffneten", "bewaffnetem", "bewaffneten"],
  "2.": ["2.", "2.", "2."],
  "anfänglich": ["anfänglich", "anfänglicher", "anfängliches", "anfänglichen"],
  "alarmierend": ["alarmierend", "alarmierenden", "alarmierenden", "alarmierende"],
  "schwierig": ["schwierig", "schwierigen", "schwierigste", "schwierigsten"],
  "schlimm": ["schlimmsten", "schlimmsten", "schlimmen", "schlimmsten"],
  "natürlich": ["natürlich", "natürliche", "natürlichen", "natürliche"],
  "arm": ["armen", "arme", "arme", "armen"],
  "ewig": ["ewige", "ewigen", "ewiges", "ewigen"],
  "irakisch": ["irakische", "irakische", "irakischen", "irakische"],
  "künftig": ["künftig", "künftige", "künftigen", "künftigen"],
  "licht": ["lichten", "lichtere", "lichte"],
  "kurdisch": ["kurdischen", "kurdische", "kurdische", "kurdische"],
  "regelrecht": ["regelrecht", "regelrechte", "regelrechtem", "regelrechte"],
  "zweitgrößter": ["zweitgrößter", "zweitgrößten", "zweitgrößtes"],
  "männlich": ["männlich", "männliche", "männliches", "männlichen"],
  "aktuell": ["aktuellen", "aktuelle", "aktuelles", "aktuelle"],
  "vollständig": ["vollständig", "vollständige", "vollständiges", "vollständiger"],
  "willkürlich": ["willkürlich", "willkürliche", "willkürlichen", "willkürliche"],
  "übrig": ["übrigen", "übrige", "übrigen", "übrigen"],
  "beruflich": ["beruflich", "berufliche", "beruflichen", "berufliche"],
  "offen": ["offen", "offenste", "offenen", "offene"],
  "gefährlich": ["gefährlich", "gefährlicher", "gefährliches", "gefährlicher"],
  "gestiegen": ["gestiegenen", "gestiegenen", "gestiegenen", "gestiegene"],
  "traditionell": ["traditionellen", "traditionelle", "traditionellen", "traditionellen"],
  "derartig": ["derartiger", "derartigen", "derartiges", "derartige"],
  "sprachlich": ["sprachlich", "sprachliche", "sprachliches", "sprachlichen"],
  "physisch": ["physischen", "physischer", "physische", "physischen"],
  "dominiert": ["dominierte", "dominierte", "dominiertes", "dominierten"],
  "ausgeprägt": ["ausgeprägt", "ausgeprägten", "ausgeprägtes", "ausgeprägte"],
  "jugendlich": ["jugendlich", "jugendliche", "jugendliche", "jugendliche"],
  "rigide": ["rigiden", "rigiden", "rigide", "rigide"],
  "gesellschaftlich": ["gesellschaftlich", "gesellschaftliche", "gesellschaftliche", "gesellschaftliche"],
  "friedlich": ["friedlich", "friedlichen", "friedliche", "friedliche"],
  "kubanisch": ["kubanischen", "kubanischen", "kubanische"],
  "sozialistisch": ["sozialistische", "sozialistischen", "sozialistische", "sozialistischer"],
  "ökonomisch": ["ökonomisch", "ökonomische", "ökonomische", "ökonomischen"],
  "mild": ["milder", "milde", "milde"],
  "ähnlich": ["ähnlich", "ähnlichen", "ähnlichem", "ähnlichen"],
  "schwerwiegend": ["schwerwiegenden", "schwerwiegende", "schwerwiegendste", "schwerwiegende"],
  "kommunistisch": ["kommunistischen", "kommunistischen", "kommunistische", "kommunistische"],
  "freiwillig": ["freiwillig", "freiwillige", "freiwilliges", "freiwillige"],
  "unpolitisch": ["unpolitischen", "unpolitische", "unpolitischen"],
  "kostenlos": ["kostenlos", "kostenlosen", "kostenloses", "kostenlosen"],
  "bescheiden": ["bescheidener", "bescheidene", "bescheidenes", "bescheidene"],
  "gewaltsam": ["gewaltsam", "gewaltsame", "gewaltsame", "gewaltsamen"],
  "tragisch": ["tragisch", "tragische", "tragischen", "tragischen"],
  "prominent": ["prominenteste", "prominenter", "prominentestes", "prominentesten"],
  "lieb": ["liebsten", "lieben", "liebes", "lieben"],
  "militärisch": ["militärischen", "militärische", "militärische", "militärischen"],
  "historisch": ["historisch", "historischer", "historisches", "historischen"],
  "strikt": ["strikt", "strikter", "strikte", "strikte"],
  "mühsam": ["mühsam", "mühsamen", "mühsames"],
  "humanitär": ["humanitär", "humanitäre", "humanitäres", "humanitären"],
  "rot": ["roter", "rote", "roten", "rote"],
  "vereint": ["vereinten", "vereinten", "vereinten", "vereinten"],
  "begrenzt": ["begrenzt", "begrenzten", "begrenzte", "begrenzten"],
  "einvernehmlich": ["einvernehmlich", "einvernehmlichen", "einvernehmliches", "einvernehmliche"],
  "rechtzeitig": ["rechtzeitig", "rechtzeitige", "rechtzeitiges"],
  "grundsätzlich": ["grundsätzlich", "grundsätzliche", "grundsätzliche", "grundsätzliche"],
  "jeweilig": ["jeweiligen", "jeweiligen", "jeweiligen", "jeweiligen"],
  "ausreichend": ["ausreichend", "ausreichende", "ausreichendes", "ausreichende"],
  "ausführlich": ["ausführlich", "ausführlicher", "ausführlichem", "ausführliche"],
  "unangenehm": ["unangenehm", "unangenehmer", "unangenehmen", "unangenehme"],
  "eingesetzt": ["eingesetzter", "eingesetzte", "eingesetzte", "eingesetzte"],
  "vielfältig": ["vielfältiger", "vielfältiger", "vielfältigen", "vielfältigen"],
  "bedenklich": ["bedenklich", "bedenkliche", "bedenkliches", "bedenklicher"],
  "gehalten": ["gehaltenen", "gehaltenen", "gehaltenen", "gehaltenen"],
  "verbunden": ["verbundene", "verbundenen", "verbundenes", "verbundenen"],
  "endgültig": ["endgültig", "endgültige", "endgültigen", "endgültigen"],
  "gemeinnützig": ["gemeinnützigen", "gemeinnütziger", "gemeinnütziges", "gemeinnützige"],
  "erheblich": ["erheblichen", "erhebliche", "erheblichen", "erhebliche"],
  "umstritten": ["umstritten", "umstrittene", "umstrittenen", "umstrittenen"],
  "verwaltet": ["verwalteten", "verwalteten", "verwaltete"],
  "kommerziell": ["kommerzieller", "kommerzielle", "kommerzielle", "kommerziellen"],
  "rechtlich": ["rechtlich", "rechtliche", "rechtliche", "rechtlichen"],
  "vorig": ["vorigen", "vorigen", "vorigen"],
  "malerisch": ["malerisch", "malerische", "malerische", "malerischen"],
  "vorhanden": ["vorhanden", "vorhandene", "vorhandenen", "vorhandenen"],
  "halb": ["halben", "halbe", "halben", "halbe"],
  "nördlich": ["nördlich", "nördlicher", "nördlichen", "nördlichen"],
  "riesig": ["riesige", "riesige", "riesiges", "riesige"],
  "gesund": ["gesunden", "gesunder", "gesundes", "gesunde"],
  "westdeutsch": ["westdeutschen", "westdeutsche", "westdeutschen", "westdeutschen"],
  "ostdeutsch": ["ostdeutschen", "ostdeutschen", "ostdeutsche", "ostdeutschen"],
  "zunehmend": ["zunehmend", "zunehmende", "zunehmendem", "zunehmenden"],
  "norddeutsch": ["norddeutschen", "norddeutschen", "norddeutsches", "norddeutschen"],
  "kollektiv": ["kollektiv", "kollektiver", "kollektive", "kollektiver"],
  "selbständig": ["selbständig", "selbständiger", "selbständiges", "selbständige"],
  "örtlich": ["örtlichen", "örtliche", "örtlichen", "örtlichen"],
  "bisherig": ["bisherige", "bisherige", "bisheriges", "bisherigen"],
  "sofortig": ["sofortigen", "sofortige", "sofortige"],
  "einfach": ["einfacheren", "einfache", "einfachen", "einfacher"],
  "dramatisch": ["dramatisch", "dramatischen", "dramatisches", "dramatischsten"],
  "dänisch": ["dänische", "dänischen", "dänische", "dänische"],
  "kurz": ["kurz", "kurzen", "kurzem", "kurze"],
  "positiv": ["positiv", "positive", "positives", "positiven"],
  "westeuropäisch": ["westeuropäischen", "westeuropäischen", "westeuropäischen", "westeuropäischen"],
  "5.": ["5.", "5.", "5."],
  "dauerhaft": ["dauerhafter", "dauerhafte", "dauerhaftes", "dauerhafte"],
  "ukrainisch": ["ukrainische", "ukrainischen", "ukrainische", "ukrainischen"],
  "kommend": ["kommenden", "kommende", "kommende", "kommenden"],
  "günstig": ["günstig", "günstigen", "günstigeres", "günstigen"],
  "laufend": ["laufenden", "laufenden", "laufenden", "laufenden"],
  "hiesig": ["hiesige", "hiesige", "hiesige", "hiesigen"],
  "italienisch": ["italienischen", "italienische", "italienischen", "italienische"],
  "japanisch": ["japanischen", "japanischen", "japanische", "japanischen"],
  "funktionierend": ["funktionierenden", "funktionierende", "funktionierende", "funktionierende"],
  "ansässig": ["ansässiger", "ansässigen", "ansässigen", "ansässigen"],
  "beschlossen": ["beschlossenen", "beschlossene", "beschlossene", "beschlossenen"],
  "steigend": ["steigend", "steigende", "steigenden", "steigende"],
  "echt": ["echte", "echte", "echtes", "echten"],
  "dominierend": ["dominierende", "dominierende", "dominierenden", "dominierenden"],
  "langwierig": ["langwierig", "langwierige", "langwierigen", "langwierigen"],
  "mittelfristig": ["mittelfristig", "mittelfristige", "mittelfristiges", "mittelfristigen"],
  "nötig": ["nötig", "nötige", "nötige", "nötigen"],
  "wirksam": ["wirksam", "wirksame", "wirksamen", "wirksame"],
  "umfangreich": ["umfangreichste", "umfangreicher", "umfangreiches", "umfangreichsten"],
  "französisch": ["französischen", "französischen", "französischen", "französischen"],
  "formell": ["formellen", "formelle", "formelles", "formelle"],
  "geführt": ["geführten", "geführte", "geführten", "geführte"],
  "geschlossen": ["geschlossenen", "geschlossenen", "geschlossenes", "geschlossene"],
  "vorläufig": ["vorläufig", "vorläufige", "vorläufiges", "vorläufigen"],
  "geheim": ["geheimen", "geheime", "geheime", "geheimer"],
  "griechisch": ["griechisch", "griechische", "griechischen", "griechische"],
  "konservativ": ["konservativ", "konservativer", "konservativen", "konservativen"],
  "gehörend": ["gehörende", "gehörenden", "gehörende", "gehörenden"],
  "gesamt": ["gesamten", "gesamte", "gesamten", "gesamten"],
  "bestehend": ["bestehenden", "bestehende", "bestehende", "bestehenden"],
  "offensichtlich": ["offensichtlich", "offensichtlichen", "offensichtliches"],
  "wachsend": ["wachsendem", "wachsenden", "wachsenden", "wachsenden"],
  "marode": ["maroden", "maroden", "marode", "marode"],
  "rein": ["rein", "reine", "reines", "reinen"],
  "finanziell": ["finanziellen", "finanzielle", "finanzielle", "finanziellen"],
  "rege": ["reger", "rege", "reges"],
  "feindselig": ["feindselig", "feindseligen", "feindseliges"],
  "biologisch": ["biologische", "biologische", "biologische", "biologischen"],
  "aktiv": ["aktiver", "aktiver", "aktive", "aktive"],
  "menschlich": ["menschliche", "menschliche", "menschlichen", "menschliche"],
  "schwedisch": ["schwedische", "schwedischen", "schwedischen", "schwedischen"],
  "erhöht": ["erhöhten", "erhöhte", "erhöhtes", "erhöhten"],
  "gesundheitlich": ["gesundheitlichen", "gesundheitliche", "gesundheitliche", "gesundheitliche"],
  "krank": ["krank", "kranke", "kranke", "kranke"],
  "verschärft": ["verschärften", "verschärfter", "verschärften"],
  "ideal": ["ideale", "ideale", "ideales", "ideale"],
  "us-amerikanisch": ["us-amerikanische", "us-amerikanische", "us-amerikanischem", "us-amerikanischen"],
  "schwach": ["schwach", "schwache", "schwaches", "schwächeren"],
  "chinesisch": ["chinesische", "chinesischen", "chinesische", "chinesischen"],
  "interessiert": ["interessiert", "interessierten", "interessierten", "interessierte"],
  "plötzlich": ["plötzlich", "plötzliche", "plötzliches", "plötzlichen"],
  "einflußreich": ["einflußreicher", "einflußreiche", "einflußreichen", "einflußreichsten"],
  "liberal": ["liberaler", "liberale", "liberales", "liberalen"],
  "erfahren": ["erfahrener", "erfahrenen", "erfahrenes", "erfahrene"],
  "leicht": ["leicht", "leichtere", "leichten", "leichten"],
  "leer": ["leerer", "leere", "leeres", "leeren"],
  "vergeblich": ["vergeblich", "vergebliche", "vergeblichen", "vergeblichen"],
  "angekündigt": ["angekündigten", "angekündigten", "angekündigte", "angekündigten"],
  "vereinbart": ["vereinbarte", "vereinbarter", "vereinbarte", "vereinbarte"],
  "russisch": ["russischen", "russischen", "russische", "russischen"],
  "eindeutig": ["eindeutig", "eindeutigen", "eindeutiges", "eindeutigen"],
  "19.": ["19.", "19.", "19."],
  "lebend": ["lebende", "lebende", "lebendes", "lebender"],
  "kalt": ["kalten", "kalte", "kaltes", "kalten"],
  "definitiv": ["definitiv", "definitive", "definitiven"],
  "ruhig": ["ruhig", "ruhigen", "ruhigeres", "ruhigere"],
  "rauh": ["rauher", "rauher", "rauhen", "rauhere"],
  "katholisch": ["katholischen", "katholischen", "katholisches", "katholischen"],
  "erschienen": ["erschienenem", "erschienene", "erschienenen", "erschienenen"],
  "kirchlich": ["kirchlich", "kirchlichen", "kirchliche", "kirchlichen"],
  "kosmisch": ["kosmischen", "kosmischen", "kosmisches"],
  "aufgeklärt": ["aufgeklärter", "aufgeklärter", "aufgeklärten", "aufgeklärten"],
  "spirituell": ["spirituell", "spirituelle", "spirituelles", "spirituellen"],
  "ethisch": ["ethischer", "ethische", "ethische", "ethischen"],
  "unbekannt": ["unbekannter", "unbekannten", "unbekanntes", "unbekannten"],
  "theologisch": ["theologischem", "theologischer", "theologische", "theologischen"],
  "evangelisch": ["evangelischen", "evangelischen", "evangelische", "evangelischen"],
  "produktiv": ["produktive", "produktive", "produktives", "produktive"],
  "gerichtet": ["gerichteter", "gerichtete", "gerichtetes", "gerichteten"],
  "solidarisch": ["solidarisch", "solidarische", "solidarisches", "solidarische"],
  "afrikanisch": ["afrikanischen", "afrikanische", "afrikanischen", "afrikanischen"],
  "ablehnend": ["ablehnend", "ablehnende", "ablehnenden"],
  "scharf": ["scharfen", "scharfe", "scharfen", "scharfe"],
  "künstlich": ["künstlich", "künstliche", "künstlichen", "künstlichen"],
  "schwarz": ["schwarz", "schwarzen", "schwarzem", "schwarze"],
  "völlig": ["völlig", "völligen", "völligen"],
  "erneut": ["erneut", "erneute", "erneutes", "erneute"],
  "genannt": ["genannten", "genannte", "genanntes", "genannte"],
  "sinkend": ["sinkenden", "sinkenden", "sinkende", "sinkenden"],
  "führend": ["führende", "führende", "führende", "führende"],
  "christlich": ["christlicher", "christlichen", "christlichen", "christlichen"],
  "mangelnd": ["mangelnden", "mangelnde", "mangelndes", "mangelnde"],
  "ein": ["eine", "eine", "eine"],
  "falsch": ["falsch", "falschen", "falsche", "falschen"],
  "brasilianisch": ["brasilianischen", "brasilianischer", "brasilianisches", "brasilianischen"],
  "bekannt": ["bekannt", "bekannte", "bekanntes", "bekannte"],
  "illegal": ["illegal", "illegaler", "illegalen", "illegale"],
  "langjährig": ["langjährige", "langjährige", "langjährige", "langjährige"],
  "besetzt": ["besetzt", "besetzter", "besetzten", "besetzten"],
  "entsprechend": ["entsprechend", "entsprechende", "entsprechendes", "entsprechende"],
  "bayerisch": ["bayerischem", "bayerische", "bayerischen", "bayerischen"],
  "östlich": ["östlich", "östlichen", "östlichen", "östlichen"],
  "moldawisch": ["moldawischer", "moldawischen", "moldawische", "moldawischen"],
  "strategisch": ["strategisch", "strategische", "strategische", "strategischen"],
  "umkämpft": ["umkämpften", "umkämpfte", "umkämpfte", "umkämpften"],
  "einberufen": ["einberufenen", "einberufene", "einberufenes"],
  "gerichtlich": ["gerichtlich", "gerichtliche", "gerichtliches", "gerichtliche"],
  "einstig": ["einstige", "einstiger", "einstige", "einstigen"],
  "gewählt": ["gewählten", "gewählten", "gewählte", "gewählten"],
  "derzeitig": ["derzeitige", "derzeitige", "derzeitige", "derzeitigen"],
  "strukturell": ["strukturelle", "strukturelle", "strukturellen", "strukturellen"],
  "sinnvoll": ["sinnvoll", "sinnvolle", "sinnvollen", "sinnvolle"],
  "18.": ["18.", "18.", "18."],
  "unerwünscht": ["unerwünscht", "unerwünschte", "unerwünschtes", "unerwünschte"],
  "israelisch": ["israelischer", "israelischen", "israelischen", "israelischer"],
  "eigenständig": ["eigenständig", "eigenständige", "eigenständiges", "eigenständigen"],
  "palästinensisch": ["palästinensische", "palästinensischen", "palästinensisches", "palästinensischen"],
  "arabisch": ["arabischer", "arabischen", "arabischen", "arabischen"],
  "dortig": ["dortigen", "dortigen", "dortige", "dortigen"],
  "gebildet": ["gebildet", "gebildete", "gebildete", "gebildeten"],
  "städtisch": ["städtische", "städtische", "städtischen", "städtischen"],
  "mexikanisch": ["mexikanischen", "mexikanischen", "mexikanische", "mexikanischen"],
  "populär": ["populären", "populäre", "populäres", "populäre"],
  "sozialdemokratisch": ["sozialdemokratischen", "sozialdemokratische", "sozialdemokratische", "sozialdemokratische"],
  "moslemisch": ["moslemischer", "moslemische", "moslemischen", "moslemischen"],
  "bevölkerungsreich": ["bevölkerungsreichsten", "bevölkerungsreichster", "bevölkerungsreichen", "bevölkerungsreichen"],
  "3.": ["3.", "3.", "3."],
  "amtlich": ["amtlich", "amtliche", "amtliches", "amtlichen"],
  "algerisch": ["algerischen", "algerische", "algerische", "algerischen"],
  "verändert": ["veränderten", "veränderte", "veränderten", "veränderte"],
  "kostengünstig": ["kostengünstiger", "kostengünstigste", "kostengünstigeren", "kostengünstigere"],
  "besonderer": ["besondern", "besondere", "besonderem", "besondere"],
  "religiös": ["religiöser", "religiöse", "religiöses", "religiöse"],
  "entfernt": ["entfernt", "entfernten", "entfernten", "entfernte"],
  "real": ["real", "realen", "realen", "reale"],
  "durchschnittlich": ["durchschnittlich", "durchschnittlichen", "durchschnittliches", "durchschnittlichen"],
  "weltweit": ["weltweit", "weltweite", "weltweiten", "weltweiten"],
  "überraschend": ["überraschend", "überraschende", "überraschende", "überraschende"],
  "siebter": ["siebten", "siebten", "siebtes"],
  "geprägt": ["geprägt", "geprägten", "geprägte", "geprägten"],
  "portugiesisch": ["portugiesische", "portugiesische", "portugiesische", "portugiesische"],
  "unterstützt": ["unterstützt", "unterstützten", "unterstützte"],
  "hinreichend": ["hinreichend", "hinreichende", "hinreichendes", "hinreichende"],
  "ungewöhnlich": ["ungewöhnlich", "ungewöhnliche", "ungewöhnlichen", "ungewöhnliche"],
  "polizeilich": ["polizeilichen", "polizeiliche", "polizeiliche"],
  "norwegisch": ["norwegischen", "norwegische", "norwegischem", "norwegischen"],
  "wesentlich": ["wesentlich", "wesentliche", "wesentliches", "wesentliche"],
  "verabschiedet": ["verabschiedeten", "verabschiedeten", "verabschiedete", "verabschiedeten"],
  "abgelehnt": ["abgelehnte", "abgelehnten", "abgelehnten", "abgelehnte"],
  "andauernd": ["andauernde", "andauernden", "andauerndes", "andauernden"],
  "bosnisch": ["bosnischen", "bosnische", "bosnischen", "bosnischen"],
  "breit": ["breiten", "breiten", "breites", "breite"],
  "außenpolitisch": ["außenpolitische", "außenpolitische", "außenpolitischen", "außenpolitischen"],
  "zerstört": ["zerstörten", "zerstörten", "zerstörtes", "zerstörte"],
  "brandenburgisch": ["brandenburgischen", "brandenburgischen", "brandenburgischen", "brandenburgische"],
  "chaotisch": ["chaotisch", "chaotische", "chaotisches", "chaotischer"],
  "vereinzelt": ["vereinzelt", "vereinzelte", "vereinzeltes", "vereinzelte"],
  "spanisch": ["spanischen", "spanischen", "spanischen", "spanischen"],
  "gültig": ["gültig", "gültigen", "gültigen", "gültigen"],
  "15.": ["15.", "15.", "15."],
  "innerdeutsch": ["innerdeutscher", "innerdeutschen", "innerdeutschen", "innerdeutsche"],
  "berechtigt": ["berechtigt", "berechtigter", "berechtigten", "berechtigten"],
  "vorliegend": ["vorliegende", "vorliegende", "vorliegende", "vorliegenden"],
  "fortdauernd": ["fortdauernd", "fortdauernde", "fortdauernden"],
  "stehend": ["stehenden", "stehende", "stehende", "stehenden"],
  "wiederholt": ["wiederholt", "wiederholte", "wiederholten", "wiederholter"],
  "protestantisch": ["protestantische", "protestantischen", "protestantischen", "protestantische"],
  "veröffentlicht": ["veröffentlichten", "veröffentlichten", "veröffentlichten", "veröffentlichten"],
  "erscheinend": ["erscheinenden", "erscheinenden", "erscheinenden", "erscheinenden"],
  "linker": ["linken", "linke", "linken", "linke"],
  "ausgerichtet": ["ausgerichteter", "ausgerichteten", "ausgerichtetes", "ausgerichtete"],
  "teilweise": ["teilweisen", "teilweise", "teilweises", "teilweiser"],
  "anschließend": ["anschließend", "anschließender", "anschließenden", "anschließenden"],
  "diesjährig": ["diesjährige", "diesjährige", "diesjährige", "diesjährigen"],
  "ursprünglich": ["ursprünglichen", "ursprünglichen", "ursprünglichen", "ursprünglichen"],
  "komplett": ["komplett", "komplette", "komplettes", "komplette"],
  "voll": ["vollen", "volle", "vollem", "vollen"],
  "bevorstehend": ["bevorstehenden", "bevorstehenden", "bevorstehendes", "bevorstehenden"],
  "vorletzter": ["vorletzter", "vorletzter", "vorletzten"],
  "umfassend": ["umfassend", "umfassende", "umfassenden", "umfassende"],
  "erklärt": ["erklärten", "erklärten", "erklärtes", "erklärten"],
  "stabil": ["stabilem", "stabile", "stabilen", "stabilen"],
  "gewährt": ["gewährte", "gewährte", "gewährten", "gewährten"],
  "regulär": ["regulär", "regulären", "regulären", "regulären"],
  "angeboten": ["angebotenen", "angebotene", "angebotenen", "angebotenen"],
  "normal": ["normal", "normale", "normalen", "normalen"],
  "geschäftsführend": ["geschäftsführende", "geschäftsführende", "geschäftsführendes"],
  "konsequent": ["konsequenter", "konsequenter", "konsequentes"],
  "kalifornisch": ["kalifornischen", "kalifornische", "kalifornischen", "kalifornischen"],
  "verbreitet": ["verbreitete", "verbreiteten", "verbreiteten", "verbreiteter"],
  "gegründet": ["gegründete", "gegründete", "gegründete", "gegründete"],
  "jugoslawisch": ["jugoslawischen", "jugoslawischen", "jugoslawischen", "jugoslawischen"],
  "vorgesehen": ["vorgesehenen", "vorgesehene", "vorgesehene", "vorgesehenen"],
  "liegend": ["liegenden", "liegende", "liegendes", "liegenden"],
  "südkoreanisch": ["südkoreanischen", "südkoreanische", "südkoreanische", "südkoreanischen"],
  "gelb": ["gelber", "gelber", "gelbes", "gelben"],
  "hektisch": ["hektischen", "hektischer", "hektische", "hektischeren"],
  "repräsentativ": ["repräsentativ", "repräsentativen", "repräsentatives", "repräsentativen"],
  "kommunal": ["kommunalen", "kommunaler", "kommunalen", "kommunaler"],
  "alltäglich": ["alltäglich", "alltäglichen", "alltäglichem", "alltägliche"],
  "werdend": ["werdenden", "werdenden", "werdenden", "werdenden"],
  "türkisch": ["türkischen", "türkischen", "türkisches", "türkischen"],
  "denkbar": ["denkbar", "denkbare", "denkbare"],
  "streng": ["streng", "strengen", "strengen", "strengen"],
  "vorgeschlagen": ["vorgeschlagenen", "vorgeschlagene", "vorgeschlagenen", "vorgeschlagenen"],
  "nordöstlich": ["nordöstlich", "nordöstlichsten", "nordöstlichsten"],
  "enttäuschend": ["enttäuschend", "enttäuschende", "enttäuschendes", "enttäuschenden"],
  "gesetzlich": ["gesetzlich", "gesetzlichen", "gesetzliches", "gesetzlichen"],
  "bewußt": ["bewußt", "bewußter", "bewußtes"],
  "pur": ["purer", "pure", "purem"],
  "mörderisch": ["mörderisch", "mörderische", "mörderischen", "mörderischen"],
  "wirkungsvoll": ["wirkungsvoll", "wirkungsvolle", "wirkungsvolles", "wirkungsvolle"],
  "freundlich": ["freundlich", "freundlichen", "freundliches", "freundliche"],
  "polnisch": ["polnischer", "polnischen", "polnischen", "polnische"],
  "restlich": ["restliche", "restliche", "restliche", "restlichen"],
  "technologisch": ["technologische", "technologische", "technologischen", "technologischen"],
  "verfassungswidrig": ["verfassungswidrig", "verfassungswidrige", "verfassungswidriges"],
  "sächsisch": ["sächsische", "sächsische", "sächsischen", "sächsische"],
  "üppig": ["üppigsten", "üppigere", "üppigen", "üppigen"],
  "geworden": ["gewordene", "gewordene", "gewordenen", "gewordene"],
  "negativ": ["negativ", "negativere", "negativen", "negativen"],
  "vorübergehend": ["vorübergehend", "vorübergehende", "vorübergehendes", "vorübergehende"],
  "ökologisch": ["ökologischen", "ökologische", "ökologischen", "ökologischen"],
  "intellektuell": ["intellektuell", "intellektuelle", "intellektuelles", "intellektuelle"],
  "leistungsfähig": ["leistungsfähige", "leistungsfähige", "leistungsfähiges", "leistungsfähige"],
  "kanadisch": ["kanadischen", "kanadische", "kanadischen", "kanadischen"],
  "16.": ["16.", "16.", "16."],
  "kritisiert": ["kritisierte", "kritisierte", "kritisierte"],
  "geschickt": ["geschickt", "geschickte", "geschicktes"],
  "betrieblich": ["betrieblicher", "betrieblichen", "betriebliches", "betriebliche"],
  "sechster": ["sechsten", "sechste", "sechsten"],
  "gewohnt": ["gewohnten", "gewohnte", "gewohnten", "gewohnten"],
  "dunkel": ["dunkel", "dunkle", "dunklen", "dunklen"],
  "baden-württembergisch": ["baden-württembergischen", "baden-württembergischen", "baden-württembergischen", "baden-württembergischen"],
  "monatelang": ["monatelang", "monatelangen", "monatelangen", "monatelangen"],
  "kürzlich": ["kürzlich", "kürzliche", "kürzlichen"],
  "tragfähig": ["tragfähig", "tragfähige", "tragfähigen", "tragfähigen"],
  "bedroht": ["bedrohter", "bedrohte", "bedrohten", "bedrohten"],
  "legendär": ["legendärer", "legendären", "legendären", "legendären"],
  "vorstellbar": ["vorstellbar", "vorstellbare", "vorstellbare"],
  "verpflichtet": ["verpflichtet", "verpflichteten", "verpflichtetes", "verpflichtete"],
  "geltend": ["geltend", "geltende", "geltendes", "geltenden"],
  "eingeführt": ["eingeführter", "eingeführte", "eingeführte", "eingeführte"],
  "stolz": ["stolz", "stolzer", "stolze"],
  "grün": ["grün", "grüne", "grünes", "grünen"],
  "ungarisch": ["ungarisch", "ungarischen", "ungarischen", "ungarische"],
  "korrekt": ["korrekt", "korrekte", "korrektes"],
  "kroatisch": ["kroatisch-", "kroatischen", "kroatische", "kroatischer"],
  "düster": ["düsterer", "düsteren", "düsteres", "düsteren"],
  "serbisch": ["serbischen", "serbischer", "serbischen", "serbischen"],
  "fernöstlich": ["fernöstlicher", "fernöstliche", "fernöstlichen"],
  "explosiv": ["explosiv", "explosiven", "explosiven"],
  "beredt": ["beredt", "beredten", "beredtes"],
  "miserabel": ["miserablen", "miserablen", "miserablem", "miserablen"],
  "eigentlich": ["eigentlichen", "eigentliche", "eigentliche", "eigentlichen"],
  "böse": ["böser", "böse", "böses", "bösen"],
  "psychologisch": ["psychologisch", "psychologische", "psychologischen", "psychologische"],
  "global": ["globale", "globale", "globalen", "globale"],
  "entwickelt": ["entwickeltem", "entwickelte", "entwickeltes", "entwickelten"],
  "saarländisch": ["saarländischen", "saarländischen", "saarländischen", "saarländische"],
  "zehnjährig": ["zehnjähriger", "zehnjähriger", "zehnjähriges", "zehnjährige"],
  "erkennbar": ["erkennbar", "erkennbare", "erkennbarem", "erkennbaren"],
  "faktisch": ["faktisch", "faktischen", "faktisches", "faktische"],
  "südafrikanisch": ["südafrikanischen", "südafrikanische", "südafrikanischen", "südafrikanische"],
  "erzielt": ["erzielte", "erzielte", "erzieltes", "erzielten"],
  "stalinistisch": ["stalinistische", "stalinistischen", "stalinistischen", "stalinistische"],
  "14.": ["14.", "14.", "14."],
  "königlich": ["königlich", "königlichen", "königlichen"],
  "warm": ["warm", "wärmeren", "warmes", "warmen"],
  "gleichnamig": ["gleichnamigen", "gleichnamigen", "gleichnamigen"],
  "beziffert": ["bezifferter", "bezifferte", "bezifferte", "bezifferten"],
  "thüringisch": ["thüringische", "thüringische", "thüringischen"],
  "radioaktiv": ["radioaktiven", "radioaktiver", "radioaktivem", "radioaktiver"],
  "traurig": ["traurig", "traurige", "trauriges", "traurigen"],
  "reich": ["reich", "reichen", "reiche", "reiche"],
  "unsinnig": ["unsinnig", "unsinnige", "unsinnige", "unsinnigen"],
  "angestrebt": ["angestrebte", "angestrebten", "angestrebte", "angestrebte"],
  "sachlich": ["sachlicher", "sachlicher", "sachliche", "sachlichen"],
  "überzogen": ["überzogenem", "überzogene", "überzogenen", "überzogene"],
  "äußerer": ["äußersten", "äußerster", "äußerste", "äußeren"],
  "patriotisch": ["patriotisch", "patriotische", "patriotische"],
  "pessimistisch": ["pessimistisch", "pessimistischen", "pessimistisches"],
  "ägyptisch": ["ägyptische", "ägyptischen", "ägyptisches", "ägyptische"],
  "zivil": ["zivilen", "ziviler", "zivilen", "zivilen"],
  "perfekt": ["perfekt", "perfekter", "perfektes"],
  "realistisch": ["realistisch", "realistischer", "realistisches", "realistischen"],
  "doppelt": ["doppelt", "doppelte", "doppeltes"],
  "westfälisch": ["westfälische", "westfälischen", "westfälischen"],
  "favorisiert": ["favorisierten", "favorisierten", "favorisierte"],
  "entschlossen": ["entschlossen", "entschlossene", "entschlossenes", "entschlossene"],
  "australisch": ["australische", "australische", "australische", "australische"],
  "irisch": ["irische", "irische", "irische"],
  "schmal": ["schmale", "schmalen", "schmalen", "schmalen"],
  "leise": ["leiser", "leise", "leisen", "leisen"],
  "furchtbar": ["furchtbarer", "furchtbare", "furchtbare", "furchtbarer"],
  "flüchtig": ["flüchtigen", "flüchtige", "flüchtiges", "flüchtigen"],
  "berüchtigt": ["berüchtigten", "berüchtigten", "berüchtigte", "berüchtigte"],
  "nackt": ["nacktem", "nackten", "nackte", "nackter"],
  "schön": ["schön", "schöne", "schönste", "schöne"],
  "zehnter": ["zehnte", "zehnte", "zehnte"],
  "folgend": ["folgenden", "folgender", "folgenden", "folgenden"],
  "katastrophal": ["katastrophal", "katastrophale", "katastrophale", "katastrophaler"],
  "systematisch": ["systematisch", "systematische", "systematischen"],
  "inländisch": ["inländische", "inländische", "inländische", "inländischen"],
  "vorgelegt": ["vorgelegten", "vorgelegten", "vorgelegte", "vorgelegten"],
  "prinzipiell": ["prinzipiell", "prinzipielle", "prinzipielle", "prinzipielle"],
  "fern": ["fern", "fernen", "ferneres", "fernen"],
  "herausragend": ["herausragend", "herausragende", "herausragenden", "herausragende"],
  "erstellt": ["erstellte", "erstellte", "erstelltes", "erstellten"],
  "locker": ["locker", "lockere", "lockeres", "lockere"],
  "fraglich": ["fraglich", "fraglichen", "fragliche"],
  "13.": ["13.", "13.", "13."],
  "merkwürdig": ["merkwürdig", "merkwürdiger", "merkwürdiges", "merkwürdige"],
  "unruhig": ["unruhig", "unruhigen", "unruhigen", "unruhigen"],
  "reif": ["reif", "reife", "reiferes", "reifere"],
  "schonungslos": ["schonungsloser", "schonungslose", "schonungsloses"],
  "aufgenommen": ["aufgenommenen", "aufgenommenen", "aufgenommenen", "aufgenommenen"],
  "existierend": ["existierende", "existierende", "existierenden", "existierenden"],
  "fest": ["fest", "fester", "festen", "feste"],
  "provisorisch": ["provisorischen", "provisorische", "provisorischen", "provisorischen"],
  "medizinisch": ["medizinisch", "medizinische", "medizinischen", "medizinische"],
  "deutsch-französisch": ["deutsch-französischen", "deutsch-französischer", "deutsch-französische"],
  "bitter": ["bitter", "bittere", "bitteren", "bitterer"],
  "industriell": ["industriell", "industriellen", "industriellen", "industriellen"],
  "kräftig": ["kräftig", "kräftige", "kräftiges", "kräftige"],
  "angepeilt": ["angepeilter", "angepeilten", "angepeilten", "angepeilten"],
  "nigerianisch": ["nigerianischen", "nigerianischen", "nigerianischen", "nigerianischen"],
  "unheilvoll": ["unheilvoll", "unheilvollen", "unheilvolles", "unheilvollen"],
  "koordiniert": ["koordinierten", "koordinierten", "koordinierten", "koordinierte"],
  "abgelaufen": ["abgelaufenen", "abgelaufenen", "abgelaufenen"],
  "technisch": ["technischen", "technischen", "technische", "technischen"],
  "fünfter": ["fünfte", "fünften", "fünften"],
  "schriftlich": ["schriftlich", "schriftlichen", "schriftliches", "schriftliche"],
  "selten": ["seltener", "seltenen", "seltenen", "seltenen"],
  "gelungen": ["gelungener", "gelungener", "gelungenen", "gelungene"],
  "diskutiert": ["diskutierten", "diskutierten", "diskutierte", "diskutierten"],
  "bulgarisch": ["bulgarische", "bulgarischen", "bulgarischen", "bulgarischen"],
  "veraltet": ["veraltet", "veralteten", "veraltete", "veralteten"],
  "unternehmerisch": ["unternehmerischen", "unternehmerische", "unternehmerischem", "unternehmerische"],
  "konventionell": ["konventionell", "konventioneller", "konventionelle", "konventionelle"],
  "marktwirtschaftlich": ["marktwirtschaftlich", "marktwirtschaftlichen", "marktwirtschaftlichen", "marktwirtschaftlichen"],
  "orientiert": ["orientierten", "orientierte", "orientiertes", "orientierten"],
  "beabsichtigt": ["beabsichtigten", "beabsichtigte", "beabsichtigte", "beabsichtigten"],
  "gründlich": ["gründlichen", "gründliche", "gründlichen", "gründlichen"],
  "gestrig": ["gestrigen", "gestrigen", "gestrigen"],
  "flächendeckend": ["flächendeckend", "flächendeckender", "flächendeckendes", "flächendeckenden"],
  "ergebnislos": ["ergebnislos", "ergebnislosen", "ergebnislosen", "ergebnislosen"],
  "drängend": ["drängender", "drängende", "drängendste", "drängenden"],
  "sauber": ["sauber", "sauberste", "sauberem", "sauberen"],
  "verbessert": ["verbesserten", "verbesserten", "verbessertes", "verbesserte"],
  "ausgezeichnet": ["ausgezeichnet", "ausgezeichneten", "ausgezeichneten", "ausgezeichnete"],
  "übernommen": ["übernommenen", "übernommenen", "übernommenen", "übernommene"],
  "typisch": ["typische", "typische", "typisches", "typischen"],
  "gegeben": ["gegebenen", "gegebenen", "gegebene", "gegebenen"],
  "vorzeigbar": ["vorzeigbar", "vorzeigbare", "vorzeigbaren", "vorzeigbare"],
  "legitim": ["legitimer", "legitime", "legitimes", "legitimen"],
  "sitzend": ["sitzend", "sitzende", "sitzenden", "sitzenden"],
  "taktisch": ["taktisch", "taktischen", "taktisches", "taktischen"],
  "verurteilt": ["verurteilten", "verurteilte", "verurteilte", "verurteilte"],
  "zugänglich": ["zugänglich", "zugänglichen", "zugänglichen", "zugängliche"],
  "lettisch": ["lettischem", "lettische", "lettischen", "lettische"],
  "20.": ["20.", "20.", "20."],
  "mangelhaft": ["mangelhaften", "mangelhafte", "mangelhaftem", "mangelhaften"],
  "sanft": ["sanften", "sanfte", "sanftem", "sanfte"],
  "sinnlos": ["sinnlos", "sinnlose", "sinnloses", "sinnlose"],
  "gegangen": ["gegangenen", "gegangene", "gegangene"],
  "leuchtend": ["leuchtender", "leuchtenderer", "leuchtendes", "leuchtende"],
  "sexuell": ["sexuell", "sexueller", "sexuellen", "sexuelle"],
  "effizient": ["effizienter", "effizienten", "effizienteste", "effiziente"],
  "straff": ["straff", "strafferen", "straffen", "straffen"],
  "beschworen": ["beschworene", "beschworene", "beschworene"],
  "finanzpolitisch": ["finanzpolitisch", "finanzpolitischer", "finanzpolitisches", "finanzpolitische"],
  "dominikanisch": ["dominikanischen", "dominikanischen", "dominikanischem"],
  "zairisch": ["zairischen", "zairische", "zairischen", "zairischen"],
  "speziell": ["speziellen", "speziellen", "spezielles", "spezielle"],
  "zukünftig": ["zukünftig", "zukünftige", "zukünftigen", "zukünftigen"],
  "intelligent": ["intelligente", "intelligente", "intelligentes", "intelligente"],
  "nachhaltig": ["nachhaltig", "nachhaltige", "nachhaltigen", "nachhaltigsten"],
  "volkswirtschaftlich": ["volkswirtschaftlich", "volkswirtschaftliche", "volkswirtschaftlichen", "volkswirtschaftliche"],
  "nordrhein-westfälisch": ["nordrhein-westfälische", "nordrhein-westfälische", "nordrhein-westfälischen", "nordrhein-westfälischen"],
  "jahrzehntelang": ["jahrzehntelang", "jahrzehntelange", "jahrzehntelanges", "jahrzehntelangen"],
  "schleswig-holsteinisch": ["schleswig-holsteinische", "schleswig-holsteinische", "schleswig-holsteinischen"],
  "kontrolliert": ["kontrollierten", "kontrollierten", "kontrolliertes", "kontrollierten"],
  "beispiellos": ["beispiellos", "beispiellose", "beispiellosen", "beispiellose"],
  "vierter": ["vierten", "vierten", "vierten"],
  "stammend": ["stammende", "stammende", "stammenden", "stammenden"],
  "geboren": ["geborene", "geborene", "gebohrnes", "geborenen"],
  "verheerend": ["verheerend", "verheerenden", "verheerenden", "verheerenden"],
  "elektrisch": ["elektrischen", "elektrischer", "elektrisches", "elektrischen"],
  "brennend": ["brennenden", "brennender", "brennenden", "brennenden"],
  "unseriös": ["unseriös", "unseriöse", "unseriöses", "unseriöser"],
  "jordanisch": ["jordanische", "jordanische", "jordanischen"],
  "total": ["total", "totalen", "totale"],
  "interessant": ["interessant", "interessanteste", "interessantes", "interessante"],
  "niederländisch": ["niederländische", "niederländische", "niederländischen", "niederländischen"],
  "begonnen": ["begonnenen", "begonnenen", "begonnene", "begonnenen"],
  "rheinland-pfälzisch": ["rheinland-pfälzischen", "rheinland-pfälzische", "rheinland-pfälzische", "rheinland-pfälzischen"],
  "gefordert": ["geforderte", "geforderten", "geforderten", "geforderten"],
  "unnötig": ["unnötiger", "unnötigen", "unnötiges", "unnötige"],
  "gewöhnlich": ["gewöhnlich", "gewöhnlichen", "gewöhnlichen", "gewöhnliche"],
  "tschechisch": ["tschechischen", "tschechische", "tschechischen", "tschechische"],
  "initiiert": ["initiierten", "initiierte", "initiierte"],
  "einheitlich": ["einheitlich", "einheitliche", "einheitlichen", "einheitliche"],
  "tödlich": ["tödlich", "tödliche", "tödliche", "tödlichen"],
  "jüdisch": ["jüdischen", "jüdischen", "jüdischen", "jüdischen"],
  "angestammt": ["angestammte", "angestammte", "angestammtem", "angestammten"],
  "biblisch": ["biblische", "biblische", "biblischen", "biblischen"],
  "kühn": ["kühn", "kühne", "kühnes", "kühnsten"],
  "verrückt": ["verrückter", "verrückte", "verrückte"],
  "gewaltfrei": ["gewaltfrei", "gewaltfreien", "gewaltfreies"],
  "verwirrend": ["verwirrend", "verwirrenden", "verwirrenden", "verwirrende"],
  "alleinig": ["alleiniger", "alleinige", "alleiniges"],
  "blau": ["blauen", "blaue", "blaues", "blauen"],
  "duftend": ["duftenden", "duftenden", "duftendem", "duftenden"],
  "fein": ["feinen", "feine", "feines", "feinen"],
  "unsicher": ["unsicher", "unsichere", "unsichere"],
  "fällig": ["fällige", "fällige", "fällige", "fällige"],
  "verordnet": ["verordneten", "verordneten", "verordnete", "verordneten"],
  "exklusiv": ["exklusiv", "exklusive", "exklusives"],
  "begeistert": ["begeistert", "begeisterter", "begeistertes", "begeisterte"],
  "klassisch": ["klassischen", "klassische", "klassischen", "klassische"],
  "erstaunlich": ["erstaunlich", "erstaunliche", "erstaunliche", "erstaunliche"],
  "passiv": ["passiv", "passive", "passive"],
  "wild": ["wilde", "wilden", "wilde", "wilden"],
  "zählend": ["zählende", "zählende", "zählenden"],
  "gewünscht": ["gewünschte", "gewünschte", "gewünschten", "gewünschten"],
  "golden": ["goldenen", "goldenen", "goldene", "goldene"],
  "intakt": ["intakt", "intakter", "intaktes", "intakte"],
  "human": ["human", "humanen", "humanes"],
  "ausgeglichen": ["ausgeglichen", "ausgeglichenen", "ausgeglichenes"],
  "englisch": ["englische", "englischen", "englischen", "englischen"],
  "fatal": ["fatale", "fatale", "fatalen", "fatalen"],
  "überdurchschnittlich": ["überdurchschnittlich", "überdurchschnittliche", "überdurchschnittlichem", "überdurchschnittliche"],
  "verkehrspolitisch": ["verkehrspolitische", "verkehrspolitische", "verkehrspolitisches", "verkehrspolitische"],
  "engagiert": ["engagierten", "engagierten", "engagierten", "engagierte"],
  "innovativ": ["innovativ", "innovative", "innovative", "innovativer"],
  "befristet": ["befristeten", "befristete", "befristetes", "befristeten"],
  "abstrakt": ["abstrakt", "abstrakte", "abstraktes", "abstrakte"],
  "tariflich": ["tariflich", "tarifliche", "tarifliches", "tariflichen"],
  "verfügbar": ["verfügbar", "verfügbarer", "verfügbaren", "verfügbaren"],
  "unabsehbar": ["unabsehbaren", "unabsehbare", "unabsehbarem", "unabsehbare"],
  "gewerkschaftlich": ["gewerkschaftlich", "gewerkschaftlichen", "gewerkschaftlichen", "gewerkschaftlichen"],
  "pädagogisch": ["pädagogisch", "pädagogischen", "pädagogischen", "pädagogische"],
  "süß": ["süß", "süße", "süße", "süßen"],
  "munter": ["munter", "munteren", "muntere"],
  "außergewöhnlich": ["außergewöhnlich", "außergewöhnliche", "außergewöhnlichen", "außergewöhnliche"],
  "attraktiv": ["attraktiver", "attraktivere", "attraktiven", "attraktive"],
  "solide": ["solide", "solide", "solides", "solide"],
  "ängstlich": ["ängstlich", "ängstlichen", "ängstliches", "ängstlicher"],
  "wirkend": ["wirkenden", "wirkenden", "wirkende", "wirkenden"],
  "13jährig": ["13jährig", "13jährige", "13jährigen"],
  "poetisch": ["poetischer", "poetischer", "poetischen"],
  "szenisch": ["szenisch", "szenische", "szenischen", "szenische"],
  "zeitgenössisch": ["zeitgenössischen", "zeitgenössischer", "zeitgenössischen", "zeitgenössische"],
  "sensibel": ["sensiblen", "sensible", "sensibles", "sensiblen"],
  "spezifisch": ["spezifischen", "spezifische", "spezifisches", "spezifische"],
  "formuliert": ["formulierten", "formulierte", "formulierte", "formulierte"],
  "bemerkenswert": ["bemerkenswert", "bemerkenswerte", "bemerkenswertes", "bemerkenswertesten"],
  "erwartet": ["erwartete", "erwarteten", "erwarteten", "erwarteten"],
  "unprofessionell": ["unprofessionell", "unprofessionelle", "unprofessionelles"],
  "geistig": ["geistig", "geistigen", "geistiges", "geistigen"],
  "jämmerlich": ["jämmerlich", "jämmerlichen", "jämmerliche"],
  "dumpf": ["dumpfe", "dumpfe", "dumpfes", "dumpfen"],
  "wunderbar": ["wunderbar", "wunderbare", "wunderbaren", "wunderbare"],
  "stürmisch": ["stürmisch", "stürmische", "stürmische", "stürmischen"],
  "widerlich": ["widerlicher", "widerliche", "widerliches"],
  "behutsam": ["behutsam", "behutsame", "behutsames"],
  "grandios": ["grandiosen", "grandioser", "grandiosen", "grandiosen"],
  "ungeheuer": ["ungeheuer", "ungeheure", "ungeheures", "ungeheuren"],
  "islamistisch": ["islamistische", "islamistische", "islamistische", "islamistischer"],
  "individuell": ["individuelle", "individuellen", "individuellen", "individuellen"],
  "bewegt": ["bewegt", "bewegte", "bewegten", "bewegte"],
  "verdient": ["verdiente", "verdienten", "verdientes", "verdienter"],
  "pragmatisch": ["pragmatisch", "pragmatische", "pragmatisches"],
  "dreitägig": ["dreitägigen", "dreitägigen", "dreitägiges"],
  "unerträglich": ["unerträglicher", "unerträgliche", "unerträglichen"],
  "römisch": ["römischen", "römische", "römischen", "römischen"],
  "unbedeutend": ["unbedeutend", "unbedeutenden", "unbedeutende", "unbedeutende"],
  "beeindruckend": ["beeindruckender", "beeindruckende", "beeindruckendes"],
  "erwähnt": ["erwähnten", "erwähnte", "erwähnten", "erwähnten"],
  "festgelegt": ["festgelegten", "festgelegte", "festgelegte", "festgelegten"],
  "gesunken": ["gesunkenen", "gesunkene", "gesunkene", "gesunkenen"],
  "künstlerisch": ["künstlerischen", "künstlerischer", "künstlerischem", "künstlerischen"],
  "fürchterlich": ["fürchterlichen", "fürchterlichste", "fürchterlichsten", "fürchterlichen"],
  "harmlos": ["harmlos", "harmlosere", "harmloses", "harmlose"],
  "schleichend": ["schleichenden", "schleichende", "schleichende"],
  "institutionell": ["institutionellen", "institutioneller", "institutionelle", "institutionelle"],
  "eröffnet": ["eröffnete", "eröffnete", "eröffnete"],
  "hübsch": ["hübscher", "hübschen", "hübsche", "hübsche"],
  "auslaufend": ["auslaufenden", "auslaufende", "auslaufendem"],
  "rot-grün": ["rot-grünen", "rot-grüne", "rot-grünes", "rot-grünen"],
  "50jährig": ["50jährige", "50jährigen", "50jähriges"],
  "viertägig": ["viertägigen", "viertägige", "viertägige"],
  "sozialverträglich": ["sozialverträglichen", "sozialverträgliche", "sozialverträglichen", "sozialverträgliche"],
  "geöffnet": ["geöffneten", "geöffnete", "geöffnetes"],
  "dicht": ["dichtem", "dichten", "dichtes", "dichte"],
  "kompliziert": ["kompliziert", "komplizierte", "komplizierten", "komplizierte"],
  "monatlich": ["monatlich", "monatliche", "monatliche", "monatlichen"],
  "lebenslang": ["lebenslang", "lebenslanger", "lebenslangen", "lebenslangen"],
  "selber": ["selben", "selbe", "selben"],
  "lebendig": ["lebendigen", "lebendiger", "lebendiges", "lebendigen"],
  "indonesisch": ["indonesische", "indonesischen", "indonesischen", "indonesischen"],
  "mittelständisch": ["mittelständisch", "mittelständische", "mittelständischen", "mittelständische"],
  "zurückhaltend": ["zurückhaltend", "zurückhaltende", "zurückhaltende"],
  "postmodern": ["postmodern", "postmodernen", "postmodernes", "postmoderner"],
  "herrschend": ["herrschenden", "herrschende", "herrschenden", "herrschenden"],
  "bloß": ["bloße", "bloße", "bloßem", "bloßen"],
  "kulinarisch": ["kulinarischer", "kulinarische", "kulinarischen", "kulinarischen"],
  "holländisch": ["holländischen", "holländischen", "holländischen", "holländischer"],
  "übermäßig": ["übermäßig", "übermäßigen", "übermäßiges", "übermäßigen"],
  "eisern": ["eisernem", "eisernen", "eisernen", "eiserne"],
  "einsam": ["einsamsten", "einsamen", "einsamen", "einsame"],
  "grob": ["grob", "grober", "grobe", "gröbsten"],
  "imaginär": ["imaginären", "imaginären", "imaginäres"],
  "komplex": ["komplex", "komplexe", "komplexe", "komplexen"],
  "robust": ["robustesten", "robuste", "robuste", "robuste"],
  "dreist": ["dreist", "dreiste", "dreiste", "dreiste"],
  "belanglos": ["belanglos", "belanglose", "belangloses", "belanglosen"],
  "glücklich": ["glücklich", "glückliche", "glücklichste"],
  "geheimnisvoll": ["geheimnisvoll", "geheimnisvolle", "geheimnisvolle", "geheimnisvollen"],
  "wiederkehrend": ["wiederkehrenden", "wiederkehrende", "wiederkehrende"],
  "magisch": ["magischer", "magische", "magisches", "magische"],
  "literarisch": ["literarisch", "literarischen", "literarisches", "literarischen"],
  "strahlend": ["strahlender", "strahlende", "strahlende", "strahlenden"],
  "großzügig": ["großzügig", "großzügigen", "großzügigen", "großzügige"],
  "erbaut": ["erbaut", "erbauten", "erbaute"],
  "bunt": ["bunt", "bunten", "buntes", "bunte"],
  "quirlig": ["quirlige", "quirligen", "quirlige"],
  "inszeniert": ["inszenierten", "inszenierter", "inszenierte", "inszenierten"],
  "kompetent": ["kompetent", "kompetente", "kompetenteres", "kompetenten"],
  "großartig": ["großartig", "großartigen", "großartigen", "großartige"],
  "filmisch": ["filmisch", "filmischen", "filmische", "filmische"],
  "lyrisch": ["lyrisch", "lyrischen", "lyrische", "lyrischen"],
  "seltsam": ["seltsam", "seltsame", "seltsames", "seltsamen"],
  "dauernd": ["dauernd", "dauernde", "dauernden", "dauernden"],
  "komisch": ["komisch", "komische", "komische", "komische"],
  "fiktiv": ["fiktivem", "fiktive", "fiktives"],
  "gespalten": ["gespaltener", "gespaltene", "gespaltenes"],
  "logisch": ["logisch", "logische", "logisches", "logischen"],
  "entstanden": ["entstandenen", "entstandenen", "entstandenes", "entstandenen"],
  "abgeschlossen": ["abgeschlossen", "abgeschlossene", "abgeschlossene", "abgeschlossene"],
  "zwingend": ["zwingend", "zwingenden", "zwingende", "zwingende"],
  "moderat": ["moderat", "moderaten", "moderaten", "moderaten"],
  "bewährt": ["bewährt", "bewährten", "bewährte", "bewährten"],
  "hervorragend": ["hervorragend", "hervorragende", "hervorragendes", "hervorragender"],
  "zuverlässig": ["zuverlässiger", "zuverlässige", "zuverlässiges", "zuverlässige"],
  "geschwächt": ["geschwächt", "geschwächte", "geschwächte", "geschwächte"],
  "gedacht": ["gedachte", "gedachte", "gedachten"],
  "überschaubar": ["überschaubar", "überschaubarer", "überschaubaren", "überschaubarsten"],
  "unverwechselbar": ["unverwechselbaren", "unverwechselbare", "unverwechselbares"],
  "verantwortungsbewußt": ["verantwortungsbewußt", "verantwortungsbewußte", "verantwortungsbewußtes", "verantwortungsbewußte"],
  "beispielhaft": ["beispielhaft", "beispielhafte", "beispielhafte", "beispielhafte"],
  "unabweisbar": ["unabweisbar", "unabweisbare", "unabweisbares"],
  "konstruktiv": ["konstruktiv", "konstruktiven", "konstruktiven"],
  "kulturell": ["kulturell", "kulturelle", "kulturelles", "kulturellen"],
  "ausgestattet": ["ausgestatteten", "ausgestatteten", "ausgestattete", "ausgestatteten"],
  "himmlisch": ["himmlischen", "himmlischen", "himmlischen"],
  "militärpolitisch": ["militärpolitischer", "militärpolitischer", "militärpolitischen"],
  "sicherheitspolitisch": ["sicherheitspolitischen", "sicherheitspolitischen", "sicherheitspolitischen", "sicherheitspolitische"],
  "optisch": ["optisch", "optische", "optisches", "optischen"],
  "erregt": ["erregt", "erregte", "erregte", "erregten"],
  "fair": ["fair", "fairen", "faires", "faire"],
  "loyal": ["loyal", "loyale", "loyales"],
  "reizvoll": ["reizvollen", "reizvoller", "reizvolle", "reizvolle"],
  "zweistellig": ["zweistelligen", "zweistellige", "zweistelligen", "zweistelligen"],
  "unverzichtbar": ["unverzichtbar", "unverzichtbare", "unverzichtbares", "unverzichtbaren"],
  "postkommunistisch": ["postkommunistischen", "postkommunistische", "postkommunistischen"],
  "starr": ["starr", "starren", "starre", "starre"],
  "wirtschaftspolitisch": ["wirtschaftspolitisch", "wirtschaftspolitischen", "wirtschaftspolitischem", "wirtschaftspolitischen"],
  "rasant": ["rasant", "rasante", "rasantes"],
  "glatt": ["glatt", "glatte", "glatten", "glatte"],
  "freiwerdend": ["freiwerdender", "freiwerdende", "freiwerdende", "freiwerdenden"],
  "professionell": ["professionellen", "professionelle", "professionellem", "professionelle"],
  "bundeseigen": ["bundeseigene", "bundeseigene", "bundeseigene"],
  "spektakulär": ["spektakulären", "spektakulärer", "spektakuläre", "spektakuläre"],
  "philosophisch": ["philosophischer", "philosophische", "philosophisches", "philosophischen"],
  "anthropologisch": ["anthropologischen", "anthropologische", "anthropologisches"],
  "still": ["stiller", "stille", "stillen", "stillen"],
  "benannt": ["benannten", "benannten", "benannten", "benannten"],
  "ökumenisch": ["ökumenischen", "ökumenischen", "ökumenisches", "ökumenischen"],
  "vornehm": ["vornehm", "vornehmer", "vornehme"],
  "konjunkturell": ["konjunkturell", "konjunkturelle", "konjunkturelle", "konjunkturellen"],
  "rechtsextremistisch": ["rechtsextremistisch", "rechtsextremistischen", "rechtsextremistisches", "rechtsextremistischen"],
  "verloren": ["verlorene", "verlorene", "verlorenes", "verlorenen"],
  "unmißverständlich": ["unmißverständlich", "unmißverständliche", "unmißverständliches"],
  "bündnisgrün": ["bündnisgrüne", "bündnisgrüne", "bündnisgrünen"],
  "massenhaft": ["massenhaften", "massenhaften", "massenhaftes", "massenhaften"],
  "braun": ["braunen", "braunen", "braunen", "braune"],
  "subjektiv": ["subjektiven", "subjektive", "subjektiven", "subjektiven"],
  "venezolanisch": ["venezolanischen", "venezolanische", "venezolanischen"],
  "unterirdisch": ["unterirdischen", "unterirdischer", "unterirdischen", "unterirdischen"],
  "ausgebaut": ["ausgebaute", "ausgebauten", "ausgebautes", "ausgebaute"],
  "genutzt": ["genutzten", "genutzte", "genutzte", "genutzten"],
  "volkstümlich": ["volkstümliche", "volkstümlicher", "volkstümlichen", "volkstümlichsten"],
  "30jährig": ["30jährige", "30jähriger", "30jährigen"],
  "kontinuierlich": ["kontinuierlich", "kontinuierliche", "kontinuierlichen", "kontinuierliche"],
  "ungenügend": ["ungenügend", "ungenügende", "ungenügende", "ungenügende"],
  "betriebswirtschaftlich": ["betriebswirtschaftlich", "betriebswirtschaftliche", "betriebswirtschaftliche", "betriebswirtschaftliche"],
  "ruandisch": ["ruandische", "ruandische", "ruandisches", "ruandischen"],
  "eingeschränkt": ["eingeschränkten", "eingeschränkter", "eingeschränkten", "eingeschränkte"],
  "lebhaft": ["lebhafteren", "lebhafte", "lebhafte", "lebhaften"],
  "schrecklich": ["schrecklichen", "schreckliche", "schreckliche", "schreckliche"],
  "souverän": ["souverän", "souveräne", "souveränes", "souveräne"],
  "angesehen": ["angesehene", "angesehene", "angesehene", "angesehene"],
  "weitläufig": ["weitläufigen", "weitläufigen", "weitläufige"],
  "expansiv": ["expansive", "expansiven", "expansiven", "expansivsten"],
  "quantitativ": ["quantitativ", "quantitative", "quantitative", "quantitative"],
  "relevant": ["relevanter", "relevante", "relevantes", "relevante"],
  "kämpferisch": ["kämpferischen", "kämpferische", "kämpferisches", "kämpferischen"],
  "elitär": ["elitär", "elitären", "elitären", "elitäre"],
  "verringert": ["verringertem", "verringerten", "verringertes", "verringerten"],
  "vorgestellt": ["vorgestellte", "vorgestellte", "vorgestelltes"],
  "gängig": ["gängigen", "gängige", "gängigstes", "gängigen"],
  "nobel": ["noble", "nobler", "noblen", "nobelsten"],
  "renommiert": ["renommierte", "renommierten", "renommierten", "renommiertesten"],
  "nett": ["nett", "nette", "nettes"],
  "universell": ["universellem", "universelle", "universellen"],
  "gefeiert": ["gefeierte", "gefeierte", "gefeierte", "gefeierten"],
  "akademisch": ["akademischer", "akademischer", "akademischem", "akademische"],
  "ehrenamtlich": ["ehrenamtlich", "ehrenamtlichen", "ehrenamtliche", "ehrenamtlichen"],
  "feindlich": ["feindlich", "feindlichen", "feindliches", "feindlichen"],
  "anspruchsvoll": ["anspruchsvoll", "anspruchsvolle", "anspruchsvolles"],
  "ernstzunehmend": ["ernstzunehmender", "ernstzunehmende", "ernstzunehmende", "ernstzunehmende"],
  "berauschend": ["berauschend", "berauschende", "berauschenden"],
  "verhalten": ["verhalten", "verhaltenen", "verhaltenen"],
  "gesamtdeutsch": ["gesamtdeutsch", "gesamtdeutsche", "gesamtdeutsches", "gesamtdeutschen"],
  "asiatisch-pazifisch": ["asiatisch-pazifischen", "asiatisch-pazifische", "asiatisch-pazifischen"],
  "grau": ["grauem", "graue", "grauen", "graue"],
  "kreativ": ["kreativ", "kreativste", "kreative", "kreative"],
  "geleitet": ["geleiteten", "geleitete", "geleiteten"],
  "beherrscht": ["beherrschten", "beherrschten", "beherrschte"],
  "elterlich": ["elterlichen", "elterliche", "elterliche"],
  "atomar": ["atomaren", "atomare", "atomaren", "atomaren"],
  "neuseeländisch": ["neuseeländische", "neuseeländische", "neuseeländischen"],
  "studentisch": ["studentischen", "studentische", "studentische", "studentische"],
  "westafrikanisch": ["westafrikanischen", "westafrikanischen", "westafrikanischen"],
  "ungelöst": ["ungelöst", "ungelöste", "ungelöstes", "ungelösten"],
  "25jährig": ["25jähriger", "25jährigen", "25jährigen"],
  "bedauerlich": ["bedauerlich", "bedauerlichen", "bedauerliches", "bedauerlichen"],
  "empfunden": ["empfundenen", "empfundenen", "empfundenes", "empfundenen"],
  "unendlich": ["unendlich", "unendliche", "unendliches"],
  "einzigartig": ["einzigartig", "einzigartigen", "einzigartigen", "einzigartige"],
  "verteilt": ["verteilt", "verteilte", "verteilten", "verteilten"],
  "mathematisch": ["mathematisch", "mathematische", "mathematisches", "mathematischen"],
  "feucht": ["feuchter", "feuchte", "feuchten", "feuchte"],
  "schlagend": ["schlagende", "schlagenden", "schlagendes"],
  "unbegrenzt": ["unbegrenzt", "unbegrenzter", "unbegrenztes"],
  "apologetisch": ["apologetisch", "apologetischer", "apologetische"],
  "grausam": ["grausam", "grausamer", "grausames", "grausamen"],
  "ordnungspolitisch": ["ordnungspolitischen", "ordnungspolitischer", "ordnungspolitisches", "ordnungspolitischen"],
  "lateinamerikanisch": ["lateinamerikanische", "lateinamerikanische", "lateinamerikanische", "lateinamerikanischen"],
  "antik": ["antiken", "antiker", "antiken", "antike"],
  "handhabbar": ["handhabbarer", "handhabbare", "handhabbares"],
  "operierend": ["operierender", "operierenden", "operierenden", "operierenden"],
  "angelsächsisch": ["angelsächsischen", "angelsächsischen", "angelsächsischem", "angelsächsischen"],
  "asiatisch": ["asiatischen", "asiatische", "asiatischen", "asiatischen"],
  "heikel": ["heikler", "heikle", "heikle", "heikle"],
  "schrumpfend": ["schrumpfenden", "schrumpfender", "schrumpfenden"],
  "trocken": ["trockenen", "trockenen", "trockenes", "trockenen"],
  "aufwendig": ["aufwendigen", "aufwendiger", "aufwendige", "aufwendigen"],
  "erleichtert": ["erleichtert", "erleichterte", "erleichtertes"],
  "hannoverscher": ["hannoversche", "hannoverschen", "hannoverschen"],
  "homogen": ["homogener", "homogene", "homogenen"],
  "erreicht": ["erreichten", "erreichte", "erreichte", "erreichten"],
  "beantragt": ["beantragte", "beantragten", "beantragten", "beantragte"],
  "dazugehörig": ["dazugehörigen", "dazugehörige", "dazugehörige", "dazugehörigen"],
  "hell": ["hellen", "helle", "helle", "helle"],
  "einmalig": ["einmalige", "einmalige", "einmalige", "einmalige"],
  "isoliert": ["isoliert", "isolierte", "isolierte", "isolierte"],
  "libysch": ["libyschen", "libyschen", "libyschen", "libyschen"],
  "hinausgehend": ["hinausgehenden", "hinausgehende", "hinausgehendes", "hinausgehenden"],
  "betrieben": ["betriebene", "betriebene", "betriebene", "betriebener"],
  "badisch": ["badische", "badischen", "badischen"],
  "öffentlich-rechtlich": ["öffentlich-rechtlichen", "öffentlich-rechtlichen", "öffentlich-rechtlichen", "öffentlich-rechtlichen"],
  "original": ["originalen", "originale", "originale", "originaler"],
  "babylonisch": ["babylonisch", "babylonischer", "babylonische", "babylonischen"],
  "farbig": ["farbig", "farbigen", "farbigem"],
  "ungewohnt": ["ungewohnt", "ungewohnter", "ungewohnte", "ungewohnte"],
  "explizit": ["explizit", "explizite", "explizites", "expliziten"],
  "musikalisch": ["musikalischen", "musikalischen", "musikalische", "musikalischen"],
  "stilistisch": ["stilistisch", "stilistische", "stilistischen"],
  "primitiv": ["primitiver", "primitive", "primitiven", "primitiven"],
  "existenzbedrohend": ["existenzbedrohend", "existenzbedrohende", "existenzbedrohende"],
  "integriert": ["integrierter", "integrierten", "integriertes", "integrierte"],
  "geographisch": ["geographisch", "geographische", "geographischen", "geographische"],
  "lax": ["lax", "laxe", "laxen"],
  "rumänisch": ["rumänischen", "rumänischen", "rumänischen", "rumänische"],
  "neoliberal": ["neoliberalen", "neoliberaler", "neoliberale", "neoliberalen"],
  "betreffend": ["betreffend", "betreffende", "betreffende", "betreffenden"],
  "umweltorientiert": ["umweltorientierter", "umweltorientierten", "umweltorientiertes", "umweltorientierten"],
  "preiswert": ["preiswert", "preiswerte", "preiswertes", "preiswerte"],
  "verhängnisvoll": ["verhängnisvollen", "verhängnisvollen", "verhängnisvolle"],
  "zugeschrieben": ["zugeschriebenen", "zugeschriebene", "zugeschriebenes"],
  "weltgrößter": ["weltgrößte", "weltgrößte", "weltgrößten", "weltgrößten"],
  "operativ": ["operativen", "operative", "operatives", "operativen"],
  "fruchtbar": ["fruchtbaren", "fruchtbare", "fruchtbare"],
  "einheimisch": ["einheimischen", "einheimische", "einheimisches", "einheimischen"],
  "winzig": ["winziger", "winzige", "winzigen", "winzigen"],
  "mediterran": ["mediterranen", "mediterrane", "mediterranen"],
  "touristisch": ["touristisch", "touristische", "touristisches", "touristische"],
  "nationalstaatlich": ["nationalstaatlich", "nationalstaatlicher", "nationalstaatliches"],
  "spannend": ["spannend", "spannende", "spannenden", "spannenden"],
  "luxuriös": ["luxuriösen", "luxuriösen", "luxuriösesten", "luxuriöse"],
  "unerschöpflich": ["unerschöpflichen", "unerschöpfliche", "unerschöpfliches"],
  "schlüssig": ["schlüssig", "schlüssige", "schlüssiges"],
  "unwiderstehlich": ["unwiderstehlich", "unwiderstehliche", "unwiderstehliche"],
  "herrlich": ["herrlich", "herrliche", "herrliche"],
  "befreit": ["befreiten", "befreite", "befreiten"],
  "ärztlich": ["ärztliche", "ärztlichen", "ärztliches", "ärztlichen"],
  "alternd": ["alternden", "alternde", "alterndes"],
  "psychiatrisch": ["psychiatrischer", "psychiatrischen", "psychiatrisches", "psychiatrische"],
  "gemütlich": ["gemütliche", "gemütlicher", "gemütliches", "gemütlichen"],
  "dynamisch": ["dynamisch", "dynamische", "dynamischen", "dynamischsten"],
  "zugespitzt": ["zugespitzt", "zugespitzten", "zugespitztes"],
  "übel": ["übel", "üble", "übles", "übelsten"],
  "weltlich": ["weltlich", "weltliche", "weltlichem", "weltlichen"],
  "einfallslos": ["einfallslos", "einfallsloser", "einfallsloses"],
  "drittgrößter": ["drittgrößte", "drittgrößte", "drittgrößtes"],
  "unterzeichnet": ["unterzeichnete", "unterzeichnete", "unterzeichnete"],
  "litauisch": ["litauischen", "litauischen", "litauischen", "litauischen"],
  "aggressiv": ["aggressiv", "aggressiven", "aggressive", "aggressive"],
  "häuslich": ["häuslichen", "häusliche", "häusliche", "häuslichen"],
  "schwäbisch": ["schwäbisch", "schwäbischen", "schwäbische"],
  "faszinierend": ["faszinierend", "faszinierenden", "faszinierenden"],
  "virtuell": ["virtuellen", "virtuelle", "virtuelle", "virtuellen"],
  "göttlich": ["göttlicher", "göttlicher", "göttlichen"],
  "digital": ["digitalen", "digitaler", "digitalen", "digitale"],
  "federführend": ["federführend", "federführenden", "federführende"],
  "börsennotiert": ["börsennotierte", "börsennotierten", "börsennotiertes", "börsennotierter"],
  "karg": ["karge", "karge", "kargen"],
  "heruntergekommen": ["heruntergekommen", "heruntergekommene", "heruntergekommene"],
  "provozierend": ["provozierend", "provozierende", "provozierendem"],
  "subversiv": ["subversiven", "subversive", "subversiven"],
  "kindlich": ["kindlich", "kindliche", "kindlichen", "kindlichen"],
  "slowakisch": ["slowakisch", "slowakischer", "slowakische"],
  "unvollständig": ["unvollständig", "unvollständige", "unvollständige"],
  "quälend": ["quälenden", "quälender", "quälende"],
  "erworben": ["erworbener", "erworbenen", "erworbenem", "erworbenen"],
  "faschistisch": ["faschistischen", "faschistische", "faschistisches"],
  "luxemburgisch": ["luxemburgische", "luxemburgischer", "luxemburgischen", "luxemburgischen"],
  "thailändisch": ["thailändischen", "thailändische", "thailändischen"],
  "philippinisch": ["philippinische", "philippinische", "philippinische"],
  "blendend": ["blendend", "blendender", "blendenden"],
  "geordnet": ["geordneter", "geordneter", "geordneten"],
  "alemannisch": ["alemannisch", "alemannischen", "alemannischen"],
  "majestätisch": ["majestätisch", "majestätischen", "majestätischen", "majestätischer"],
  "kolossal": ["kolossalen", "kolossale", "kolossales"],
  "beschaulich": ["beschaulich", "beschauliche", "beschauliches"],
  "angedeutet": ["angedeuteten", "angedeutete", "angedeuteten"],
  "provinziell": ["provinziellen", "provinzielle", "provinzielle"],
  "utopisch": ["utopisch", "utopische", "utopisches"],
  "elastisch": ["elastischem", "elastischer", "elastischem", "elastischen"],
  "zollfrei": ["zollfrei", "zollfreie", "zollfreies",  }}