import test from 'tape'
import nlp from '../_lib.js'
let here = '[verb-splitter] '

test('verbs:', function (t) {
  let arr = [
    'zusammen|arbeiten',
    'aus|lachen',
    'ein|schlafen',
    'vor|lesen',
    'ab|fahren',
    'nach|hause|kommen',
    'mit|bringen',
    'an|rufen',
    'auf|stehen',
    'aus|steigen',
    'ein|kaufen',
    'vor|bereiten',
    'ab|schalten',
    'nach|denken',
    'mit|machen',
    'an|kommen',
    'auf|hören',
    'aus|ziehen',
    'ein|laden',
    'vor|stellen',
    'ab|holen',
    'nach|schauen',
    'mit|teilen',
    'an|fangen',
    'auf|passen',
    'aus|geben',
    'ein|nehmen',
    'vor|beugen',
    'ab|waschen',
    'nach|fragen',
    'mit|nehmen',
    'an|halten',
    'auf|machen',
    'aus|füllen',
    'ein|stellen',
    'vor|beigehen',
    'ab|lehnen',
    'nach|sagen',
    'mit|bekommen',
    'an|schauen',
    'auf|schreiben',
    'aus|drucken',
    'ein|ordnen',
    'vor|lesen',
    'ab|hören',
    'nach|geben',
    'mit|bringen',
    'an|rufen',
    'auf|stehen',
    'zusammen|leben',
    'aus|atmen',
    'ein|treten',
    'vor|kommen',
    'ab|warten',
    'nach|schreiben',
    'mit|lernen',
    'an|passen',
    'auf|geben',
    'aus|sehen',
    'ein|laden',
    'vor|bereiten',
    'ab|haken',
    'nach|fühlen',
    'mit|machen',
    'an|stellen',
    'auf|hören',
    'aus|ziehen',
    'ein|kaufen',
    'vor|stellen',
    'ab|holen',
    'nach|schauen',
    'mit|teilen',
    'an|kommen',
    'auf|nehmen',
    'aus|geben',
    'ein|nehmen',
    'vor|beugen',
    'ab|waschen',
    'nach|fragen',
    'mit|nehmen',
    'an|halten',
    'auf|machen',
    'aus|füllen',
    'ein|stellen',
    'vor|beigehen',
    'ab|lehnen',
    'nach|sagen',
    'mit|bekommen',
    'an|schauen',
    'auf|schreiben',
    'aus|drucken',
    'ein|ordnen',
    'vor|lesen',
    'ab|hören',
    'nach|geben',
    'mit|bringen',
    'an|rufen',
    'auf|stehen',
    'aus|denken',
    'ein|sehen',
    'vor|ziehen',
    'ab|arbeiten',
    'nach|denken',
    // zusammen|leben|lernen (to learn to live together)
  ]
  arr.forEach(str => {
    let parts = str.split(/\|/)
    let word = str.replace(/\|/, '')
    let doc = nlp(word).compute('splitter')
    t.ok(doc.has('#Verb'), word)
    let splits = doc.docs[0][0].splits || []
    t.deepEqual(parts, splits, str)
  })
  t.end()
})